# Generated by Django 6.0.5 on 2026-09-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название компании')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Логотип')),
                ('website_url', models.URLField(verbose_name='Сайт компании')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
    ]
