# Generated by Django 6.0.5 on 2026-09-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='job_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание выполняемых работ'),
        ),
    ]
